#!/usr/bin/env bash
#
#  installer for RRLpipe functions
#
#  Version 0.2 (March 20, 2020)
#
#  Copyright (c) 2020 Lela Andrews
#
#  This software is provided 'as-is', without any express or implied
#  warranty. In no event will the authors be held liable for any damages
#  arising from the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#  2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#  3. This notice may not be removed or altered from any source distribution.
#


## Check if install was executed as root
    if [[ $EUID -ne 0 ]]; then
        echo "Install must be run as root.

rerun command with \"sudo\": sudo install
" 
        exit 1
    else
        echo ""
        sleep 1
    fi

## User feedback
    echo "Preparing to install RRLseq. Finding directories...
"
    sleep 1

## Test that intended install directories are present, else run config questions
    if [[ -d "/usr/local/bin" ]]; then
        bindir="/usr/local/bin"
    else
        bindir="missing"
        echo "Install could not find \"/usr/local/bin\".

Please specify a location for command files:"
        read bindir
        echo "You entered: \"$bindir\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/lib" ]]; then
        libdir="/usr/local/lib"
    else
        libdir="missing"
        echo "Install could not find \"/usr/local/lib\".

Please specify a location for library files:"
        read libdir
        echo "You entered: \"$libdir\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/src" ]]; then
        srcdir="/usr/local/src"
    else
        srcdir="missing"
        echo "Install could not find \"/usr/local/src\".

Please specify a location for resource files:"
        read srcdir
        echo "You entered: \"$srcdir\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/share/doc" ]]; then
        docdir="/usr/local/share/doc"
    else
        docdir="missing"
        echo "Install could not find \"/usr/local/share/doc\".

Please specify a location for documentation files:"
        read docdir
        echo "You entered: \"$docdir\"
If this is correct, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/etc/bash_completion.d" ]]; then
        bacdir="/etc/bash_completion.d"
    else
        bacdir="missing"
        echo "Install could not find \"/etc/bash_completion.d\".

Please specify a location for bash completion files:"
        read docdir
        echo "You entered: \"$docdir\"
If this is correct, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi

        echo "
This will install RRLpipe to your system. Files will be placed in the following locations:
Commands:	$bindir
Libraries:	$libdir
Resources:	$srcdir
Documentation:	$docdir
Completion:	$bacdir


If you would like to proceed, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "
RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    sleep 1

## Gather remaining variables and move to repo directory
    d0=$(date)
    hn=$(hostname)
    repodir=$(pwd)
    cd $repodir

## Check for prior installation and run uninstall if necessary
    echo "Checking for prior installation.
"
    if [[ -e "$repodir/.install_log ]]; then
        echo "Prior installation found. Running uninstall first to remove old files.
"
        sudo ./uninstall
    else
        echo "No prior installation found.
"
    fi

exit 0

## Generate install log file
echo "
Installing RRLpipe to $hn ($d0).

Copying files:


" > $repodir/.install_log

## Generate uninstall file


exit 0



## Find home directory.
        bindir="$( cd "$( dirname "$0" )" && pwd )"
        repodir=$(pwd)
        cd
        homedir=$(pwd)
        cd $workdir
        echo ""

## Run install steps if .bashrc exists
    if [[ -f "$homedir/.bashrc" ]]; then
	repodir="$( cd "$( dirname "$0" )" && pwd )"
	sourceline="source $srcdir/RRLpipe_autocomplete"
	sourcecount=$(grep "$sourceline" ~/.bashrc 2>/dev/null | wc -l)
	pathline="$bindir"
	pathcount=$(grep "$pathline" ~/.bashrc 2>/dev/null | wc -l)

	if [[ "$sourcecount" == "0" ]]; then
	echo "
## Autocompletion for RRLpipe commands.
$sourceline
" >> $homedir/.bashrc

		sourcecount=$(grep $sourceline ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$sourcecount" == "0" ]]; then
		echo "Unexpected problem. Command autocompletion not configured.
		"
		elif [[ "$sourcecount" -ge "1" ]]; then
		echo "Command autocompletion successfully configured for RRLpipe.
		"
		fi

	elif [[ "$sourcecount" -ge "1" ]]; then
	echo "Command autocompletion already configured for RRLpipe.
	"
	fi

	if [[ "$pathcount" == "0" ]]; then

		bashrcpathcount=$(grep "PATH=" ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$bashrcpathcount" -ge "1" ]]; then
		quotetest=$(grep "PATH=\"" ~/.bashrc 2>/dev/null | wc -l)
			if [[ "$quotetest" == "0" ]]; then
			sed -i "s/PATH=/PATH=\"/" ~/.bashrc
			sed -i "/PATH=/ s/$/\"/" ~/.bashrc
			fi
		sed -i "/PATH/s/\"$/:TARGET/" ~/.bashrc 2>/dev/null || true
		sed -i "/PATH/s|TARGET$|$repodir/scripts\"|" ~/.bashrc 2>/dev/null || true
		else
		echo "
## Add PATH variables here.
PATH=\"\$PATH:$bindir/\"
" >> $homedir/.bashrc
		fi

		pathcount=$(grep $pathline ~/.bashrc 2>/dev/null | wc -l)
		if [[ "$pathcount" == "0" ]]; then
		echo "Unexpected problem. PATH to RRLpipe scripts not configured.
		"
		elif [[ "$pathcount" -ge "1" ]]; then
		echo "Command PATH successfully configured for RRLpipe.
		"
		fi

	elif [[ "$pathcount" -ge "1" ]]; then
	echo "Command PATH already configured for RRLpipe.
	"
	fi

source $homedir/.bashrc

	sourcecount=$(grep "$sourceline" ~/.bashrc 2>/dev/null | wc -l)
	pathcount=$(grep "$pathline" ~/.bashrc 2>/dev/null | wc -l)

	if [[ "$sourcecount" -ge "1" && "$pathcount" -ge "1" ]]; then
	echo "RRLpipe is properly configured. Restart your terminal or run:
source ~/.bashrc
	"
	else
	echo "Unexpected problem(s) encountered.
	"
		if [[ "$sourcecount" -eq "0" ]]; then
		echo "Command autocompletion not configured.
		"
		else
		echo "Command autocompletion is properly configured.
		"
		fi

		if [[ "$pathcount" -eq "0" ]]; then
		echo "Command PATH not configured.
		"
		else
		echo "Command PATH is properly configured.
		"
		fi
	fi

else
	echo "
No $homedir/.bashrc file found. You may need to manually configure RRLpipe.
	"
fi

exit 0
