#!/usr/bin/env bash
#
#  installer for RRLpipe functions
#
#  Version 0.2 (March 20, 2020)
#
#  Copyright (c) 2020 Lela Andrews
#
#  This software is provided 'as-is', without any express or implied
#  warranty. In no event will the authors be held liable for any damages
#  arising from the use of this software.
#
#  Permission is granted to anyone to use this software for any purpose,
#  including commercial applications, and to alter it and redistribute it
#  freely, subject to the following restrictions:
#
#  1. The origin of this software must not be misrepresented; you must not
#     claim that you wrote the original software. If you use this software
#     in a product, an acknowledgment in the product documentation would be
#     appreciated but is not required.
#  2. Altered source versions must be plainly marked as such, and must not be
#     misrepresented as being the original software.
#  3. This notice may not be removed or altered from any source distribution.
#


## Check if install was executed as root
    if [[ $EUID -ne 0 ]]; then
        echo "Install must be run as root.

rerun command with \"sudo\": sudo install
" 
        exit 1
    else
        echo ""
        sleep 1
    fi

## User feedback
    echo "Preparing to install RRLseq. Finding directories...
"
    sleep 1

## Test that intended install directories are present, else run config questions
    if [[ -d "/usr/local/bin" ]]; then
        bindir="/usr/local/bin"
    else
        bindir="missing"
        echo "Install could not find \"/usr/local/bin\".

Please specify a location for command files:"
        read bindir
        echo "You entered: \"$bindir\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/lib" ]]; then
        libdir0="/usr/local/lib"
    else
        libdir0="missing"
        echo "Install could not find \"/usr/local/lib\".

Please specify a location for library files:"
        read libdir
        echo "You entered: \"$libdir0\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/src" ]]; then
        srcdir="/usr/local/src"
    else
        srcdir="missing"
        echo "Install could not find \"/usr/local/src\".

Please specify a location for resource files:"
        read srcdir
        echo "You entered: \"$srcdir\"
If this is correct, type \"yes\" or type anything else to exit now."
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/usr/local/share/doc" ]]; then
        docdir="/usr/local/share/doc"
    else
        docdir="missing"
        echo "Install could not find \"/usr/local/share/doc\".

Please specify a location for documentation files:"
        read docdir
        echo "You entered: \"$docdir\"
If this is correct, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/tmp" ]]; then
        tmpdir="/tmp"
    else
        tmpdir="missing"
        echo "Install could not find \"/tmp\".

Please specify a location for temporary files:"
        read tmpdir
        echo "You entered: \"$tmpdir\"
If this is correct, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi
    if [[ -d "/etc/bash_completion.d" ]]; then
        bacdir="/etc/bash_completion.d"
    else
        bacdir="missing"
        echo "Install could not find \"/etc/bash_completion.d\".

Please specify a location for bash completion files:"
        read docdir
        echo "You entered: \"$bacdir\"
If this is correct, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "RRLpipe was not installed. Exiting.
"
            exit 1
        fi
    fi

        echo "
This will install RRLpipe to your system. Files will be placed in the following locations:
Commands:	$bindir
Libraries:	$libdir0
Resources:	$srcdir
Documentation:	$docdir
Temporary:	$tmpdir
Completion:	$bacdir


If you would like to proceed, type \"yes\" or type anything else to exit now.
"
        read yesno
        if [[ "$yesno" != "yes" ]]; then
            echo "
RRLpipe was not installed. Exiting.
"
            exit 1
        fi

    sleep 1

## Gather remaining variables and move to repo directory
    d0=$(date)
    hn=$(hostname)
    repodir=$(pwd)
    cd $repodir
    libdir="$libdir0/RRLpipe-core"

## Generate path config file
    cp $repodir/bin/.RRLpipe.config.blank $repodir/bin/.RRLpipe.config
    sed -i "s@Commands\tundefined@Commands\t$bindir@" $repodir/bin/.RRLpipe.config
    sed -i "s@Libraries\tundefined@Libraries\t$libdir@" $repodir/bin/.RRLpipe.config
    sed -i "s@Resources\tundefined@Resources\t$srcdir@" $repodir/bin/.RRLpipe.config
    sed -i "s@Documentation\tundefined@Documentation\t$docdir@" $repodir/bin/.RRLpipe.config
    sed -i "s@Temporary\tundefined@Temporary\t$tmpdir@" $repodir/bin/.RRLpipe.config
    sed -i "s@Completion\tundefined@Completion\t$bacdir@" $repodir/bin/.RRLpipe.config

## Check for prior installation and run uninstall if necessary
    echo "
Checking for prior installation.
"
    if [[ -e "$repodir/.install_log" ]]; then
        echo "Prior installation found. Running uninstall first to remove old files.
"
        sudo ./uninstall
    else
        echo "No prior installation found.
"
    fi

## Report to user and generate install log
    echo "
Installing RRLpipe.

Copying files, generating install log file and uninstallation script...
" 
    echo "
RRLpipe installation to $hn on $d0
"    > $repodir/.install_log

## Generate uninstall file
    echo "#!/usr/bin/env bash
"    > $repodir/.uninstall

## For loops to copy files and send commands to .install_log and .uninstall
## bin
    for fname in `cat $repodir/bin/.install_list`; do
        cp $repodir/bin/$fname $bindir
        echo "cp $repodir/bin/$fname $bindir" >> $repodir/.install_log
        echo "rm $bindir/$fname" >> $repodir/.uninstall
    done

## lib
    if [[ -d $libdir ]]; then
        ldir="TRUE"
    else
        mkdir $libdir
    fi
    for fname in `cat $repodir/lib/.install_list`; do
        cp $repodir/lib/RRLpipe-core/$fname $libdir/
        echo "cp $repodir/lib/RRLpipe-core/$fname $libdir" >> $repodir/.install_log
        echo "rm $libdir/$fname" >> $repodir/.uninstall
    done
    echo "rm -r $libdir" >> $repodir/.uninstall

## src
    for fname in `cat $repodir/src/.install_list`; do
        cp $repodir/src/$fname $srcdir/
        echo "cp $repodir/src/$fname $srcdir" >> $repodir/.install_log
        echo "rm $srcdir/$fname" >> $repodir/.uninstall
    done

## doc
    for fname in `cat $repodir/doc/.install_list`; do
        cp $repodir/doc/$fname $docdir/
        echo "cp $repodir/doc/$fname $docdir" >> $repodir/.install_log
        echo "rm $docdir/$fname" >> $repodir/.uninstall
    done

## completion
    for fname in `cat $repodir/etc/.install_list`; do
        cp $repodir/etc/bash_completion.d/$fname $bacdir/
        echo "cp $repodir/etc/bash_completion.d/$fname $bacdir" >> $repodir/.install_log
        echo "rm $bacdir/$fname" >> $repodir/.uninstall
    done
sleep 1

## Report to user
    echo "
RRLpipe installed. Open a new terminal.
"
exit 0

