#!/usr/bin/env bash
## Command autocompletion file for RRLpipe

_RRLpipe_completions()
{
  local cur prev opts base
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  ## Basic options to autocomplete
  opts="configure print_config check check_result help
	phix_filtering strip_primers test
	test_result tutorial
	update
        "

  ## Complete available RRLpipe command arguments
  case $prev in
	RRLpipe)
	  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	  ;;

  ## Complete options to select commands

	strip_primers)
	  local sub="help 0 1 2"
	  COMPREPLY=( $(compgen -W "${sub}" -- ${cur}) )
	  ;;
	phix_filtering)
	  local sub="help"
	  COMPREPLY=( $(compgen -W "${sub}" -- ${cur}) )
	  ;;
	configure)
	  local sub="Reference Taxonomy Tree Chimeras
		Alignment_template Alignment_lanemask BLAST_evalue
		Split_libraries_qvalue Split_libraries_minpercent
		Split_libraries_maxbad Prefix_length
		Suffix_length OTU_picker Tax_assigner
		Rarefaction_depth CPU_cores Multx_errors
		ITSx_options Cutadapt_errors help"
	  COMPREPLY=( $(compgen -W "${sub}" -- ${cur}) )
	  ;;
  esac
  return 0
}
complete -F _RRLpipe_completions RRLpipe
